### ISSUE TITLE
how to connect to wled

### ISSUE THREAD

**Issue by ra1n08** [ShiromMakkad/LedFxMobile#3]
i using LedFX app on google play store and i connect to wled device
but how, i see it have only http and https method but wled devices using e131 and udp to control via third-party app

so Do you need a bridge software for ledfx-mobile to wled device?

tks
(srr for my english)

**Comment by ShiromMakkad** [comment]
Yes, you need to host an ledfx instance somewhere and connect it to wled. I honestly wouldn't use this app anymore. Their new frontend has a PWA built in that you can add to your home screen.

**Comment by bachoo786** [comment]
> Yes, you need to host an ledfx instance somewhere and connect it to wled. I honestly wouldn't use this app anymore. Their new frontend has a PWA built in that you can add to your home screen.

sorry how does the PWA work? I tried to use your app but couldnt connect my WLED to it. I am after playing music from my phone and have the effect on the WLED. Is that possible?
